version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
      POSTGRES_DB: shareit
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge
